# Generated by Django 4.2.5 on 2023-09-19 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_entery'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entery',
            new_name='Entry',
        ),
    ]
